name: Ruby Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          echo "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}" > $HOME/.gem/credentials
          gem build brigitte.gemspec
          gem push brigitte*.gem
